openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/cameras_api/:
    get:
      operationId: listCameras
      description: API endpoint that allows cameras to be viewed or edited.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Camera'
          description: ''
      tags:
      - api
    post:
      operationId: createCamera
      description: API endpoint that allows cameras to be viewed or edited.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camera'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Camera'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Camera'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camera'
          description: ''
      tags:
      - api
  /api/cameras_api/{camera_number}/:
    get:
      operationId: retrieveCamera
      description: API endpoint that allows cameras to be viewed or edited.
      parameters:
      - name: camera_number
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camera'
          description: ''
      tags:
      - api
    put:
      operationId: updateCamera
      description: API endpoint that allows cameras to be viewed or edited.
      parameters:
      - name: camera_number
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camera'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Camera'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Camera'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camera'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCamera
      description: API endpoint that allows cameras to be viewed or edited.
      parameters:
      - name: camera_number
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camera'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Camera'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Camera'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camera'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCamera
      description: API endpoint that allows cameras to be viewed or edited.
      parameters:
      - name: camera_number
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Camera:
      type: object
      properties:
        url:
          type: string
          maxLength: 255
        multicast_address:
          type: string
          nullable: true
        multicast_port:
          type: integer
          maximum: 65535
          nullable: true
          minimum: 0
        camera_username:
          type: string
          maxLength: 32
        camera_password:
          type: string
          maxLength: 64
        camera_number:
          type: integer
          maximum: 9999999999
          minimum: 1
          format: int64
        camera_name:
          type: string
          maxLength: 100
        camera_location:
          type: string
          maxLength: 100
        matching_threshold:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1
          minimum: 0
        focus_value_threshold:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 9999
          minimum: 0
        light_level_threshold:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 255
          minimum: 0
        scheduled_hours:
          type: array
          items:
            type: integer
        scheduled_days:
          type: array
          items:
            type: integer
      required:
      - url
      - camera_number
      - camera_name
      - camera_location
