# Generated by Django 3.2.3 on 2021-11-23 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, unique=True, verbose_name='Camera URL')),
                ('camera_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)])),
                ('camera_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL friendly name')),
                ('camera_location', models.CharField(max_length=100)),
                ('image_regions', models.CharField(max_length=300)),
                ('matching_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date checked')),
            ],
        ),
        migrations.CreateModel(
            name='EngineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RUN COMPLETED', 'Finished'), ('STARTED', 'Started'), ('ERROR', 'Error')], max_length=32)),
                ('engine_process_id', models.PositiveIntegerField(default=0)),
                ('transaction_rate', models.PositiveIntegerField(default=0)),
                ('state_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='run completion time')),
            ],
        ),
        migrations.CreateModel(
            name='Licensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='license start date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='license end date')),
                ('transaction_limit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1)])),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('license_key', models.CharField(default='None', max_length=256)),
                ('license_owner', models.CharField(default='None', max_length=256)),
                ('site_name', models.CharField(default='None', max_length=256)),
                ('run_schedule', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(168), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=300, upload_to=main_menu.models.ReferenceImage.get_image_filename, verbose_name='Reference Image')),
                ('hour', models.CharField(default=main_menu.models.ReferenceImage.get_hour, max_length=2)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.camera', verbose_name='Camera')),
            ],
        ),
        migrations.CreateModel(
            name='LogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logs/%Y/%m/%d')),
                ('matching_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('region_scores', models.JSONField(default=dict)),
                ('current_matching_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('focus_value', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('action', models.CharField(max_length=20, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.camera')),
            ],
        ),
    ]
