<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-11-23 12:49

=======
# Generated by Django 4.1.7 on 2023-03-25 09:31

from django.conf import settings
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_menu.models
<<<<<<< HEAD
=======
import simple_history.models
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('url', models.CharField(max_length=300, unique=True, verbose_name='Camera URL')),
                ('camera_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)])),
                ('camera_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL friendly name')),
                ('camera_location', models.CharField(max_length=100)),
                ('image_regions', models.CharField(max_length=300)),
                ('matching_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
=======
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Camera URL')),
                ('multicast_address', models.GenericIPAddressField(blank=True, default=None, null=True, protocol='IPv4', unique=True)),
                ('camera_number', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)])),
                ('camera_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL friendly name')),
                ('camera_location', models.CharField(max_length=100)),
                ('image_regions', models.CharField(default='[]', max_length=300)),
                ('matching_threshold', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('focus_value_threshold', models.DecimalField(decimal_places=2, default=200, max_digits=6, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('light_level_threshold', models.DecimalField(decimal_places=2, default=120, max_digits=5, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date checked')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='DaysOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=12, verbose_name='Days in the week')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
            name='EngineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RUN COMPLETED', 'Finished'), ('STARTED', 'Started'), ('ERROR', 'Error')], max_length=32)),
                ('engine_process_id', models.PositiveIntegerField(default=0)),
                ('transaction_rate', models.PositiveIntegerField(default=0)),
                ('state_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='run completion time')),
<<<<<<< HEAD
=======
                ('number_failed_images', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HoursInDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_in_the_day', models.IntegerField(verbose_name='Hours in the Day')),
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
            ],
        ),
        migrations.CreateModel(
            name='Licensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='license start date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='license end date')),
                ('transaction_limit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1)])),
<<<<<<< HEAD
                ('transaction_count', models.PositiveIntegerField(default=0)),
=======
                ('transaction_count', models.IntegerField(default=0)),
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
                ('license_key', models.CharField(default='None', max_length=256)),
                ('license_owner', models.CharField(default='None', max_length=256)),
                ('site_name', models.CharField(default='None', max_length=256)),
                ('run_schedule', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(168), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=300, upload_to=main_menu.models.ReferenceImage.get_image_filename, verbose_name='Reference Image')),
                ('hour', models.CharField(default=main_menu.models.ReferenceImage.get_hour, max_length=2)),
<<<<<<< HEAD
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.camera', verbose_name='Camera')),
=======
                ('light_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.camera', verbose_name='Camera Name and Number')),
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
            ],
        ),
        migrations.CreateModel(
            name='LogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logs/%Y/%m/%d')),
                ('matching_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('region_scores', models.JSONField(default=dict)),
                ('current_matching_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('focus_value', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
<<<<<<< HEAD
                ('action', models.CharField(max_length=20, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.camera')),
            ],
=======
                ('light_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('action', models.CharField(max_length=20, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.camera', verbose_name='Camera Name and Number')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReferenceImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=300, verbose_name='Reference Image')),
                ('hour', models.CharField(default=main_menu.models.ReferenceImage.get_hour, max_length=2)),
                ('light_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_menu.camera', verbose_name='Camera Name and Number')),
            ],
            options={
                'verbose_name': 'historical reference image',
                'verbose_name_plural': 'historical reference images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLogImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=100)),
                ('matching_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('region_scores', models.JSONField(default=dict)),
                ('current_matching_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('focus_value', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('light_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('action', models.CharField(max_length=20, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_menu.camera', verbose_name='Camera Name and Number')),
            ],
            options={
                'verbose_name': 'historical log image',
                'verbose_name_plural': 'historical log images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCamera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=255, verbose_name='Camera URL')),
                ('multicast_address', models.GenericIPAddressField(blank=True, db_index=True, default=None, null=True, protocol='IPv4')),
                ('camera_number', models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)])),
                ('camera_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name='URL friendly name')),
                ('camera_location', models.CharField(max_length=100)),
                ('image_regions', models.CharField(default='[]', max_length=300)),
                ('matching_threshold', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('focus_value_threshold', models.DecimalField(decimal_places=2, default=200, max_digits=6, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('light_level_threshold', models.DecimalField(decimal_places=2, default=120, max_digits=5, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date checked')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical camera',
                'verbose_name_plural': 'historical cameras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='camera',
            name='scheduled_days',
            field=models.ManyToManyField(blank=True, to='main_menu.daysofweek'),
        ),
        migrations.AddField(
            model_name='camera',
            name='scheduled_hours',
            field=models.ManyToManyField(blank=True, to='main_menu.hoursinday'),
>>>>>>> added heap of changes that were not pushed up since september 2022.  Some known - fixed bug with pdf creation where log or reference image were deleted.  Added code to push message to synergy. Current version has Synergy skin
        ),
    ]
